on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read   # This is required for actions/checkout@v2
      
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: aws sts get-caller-identity
      # sam build 
      - run: sam build ##--use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - name: Deploy to Bob's dev account, us-east-1
        run: sam deploy --template .aws-sam/build/template.yaml --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --image-repository 292556232487.dkr.ecr.us-east-1.amazonaws.com/helloworld --capabilities CAPABILITY_IAM --region us-east-1 

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-west-2

      - name: Deploy to Bob's dev account, us-west-2
        run: sam deploy --template .aws-sam/build/template.yaml --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --image-repository 292556232487.dkr.ecr.eu-west-2.amazonaws.com/helloworld --capabilities CAPABILITY_IAM --region us-west-2 

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-1

      - name: Deploy to Bob's dev account, eu-west-1
        run: sam deploy --template .aws-sam/build/template.yaml --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --image-repository 292556232487.dkr.ecr.eu-west-1.amazonaws.com/helloworld --capabilities CAPABILITY_IAM --region eu-west-1 

      
